### PR TITLE
money stats now update on continue button click

### PR DESCRIPTION
**Pull request by JacobSnover**
In respondToAction I added an algorithm to update the money stats, while trying to keep current visuals intact. Had to strip out special chars from moneytext, and then coverted anything over one thousand dollars as a truncated $1.7K as opposed to $1,700K. Have not seen a reason to subtract money yet, so that feature is not in this algo yet. Have plans to refactor.

### CODE REVIEW

**Comment by JacobSnover** [comment]
Look at lines 144 - 157 to see my additions

**Comment by anthkris** [comment]
@JacobSnover What are your thoughts about the way money is displayed? Is it stupid? Might it be better to just show all of the digits, instead of the K? Also what do you think about the other stats?

**Comment by JacobSnover** [comment]
I added functions to handle updating all the stats now. There is different code to make the money stat display 1 of either ways, currency or decimal.

**Comment by anthkris** [comment]
@JacobSnover LGTM!

**Pull request merged**
